# docker-compose.yml
version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "4000:4000"
    environment:
      - NODE_ENV=development

  # frontend:
  #   build: ./frontend
  #   ports:
  #     - "3000:3000"
  #   volumes:
  #     - ./frontend:/app
  #   environment:
  #     - NODE_ENV=development

  # redis:
  #   image: redis:latest
  #   ports:
  #     - "6379:6379"

  # mongodb:
  #   image: mongo:latest
  #   ports:
  #     - "27017:27017"
