# render.yaml
services:
  - type: web
    name: backend
    runtime: docker
    dockerfilePath: ./backend/Dockerfile
    envVars:
      - key: NODE_ENV
        value: development
    port: 4000

  # - type: web
  #   name: frontend
  #   runtime: docker
  #   dockerfilePath: ./frontend/Dockerfile
  #   envVars:
  #     - key: NODE_ENV
  #       value: development
  #   port: 3000

  # - type: redis
  #   name: redis
  #   plan: free  # Assuming Redis can use the free plan, please adjust if needed

  # - type: mongodb
  #   name: mongodb
  #   plan: free  # Assuming MongoDB can use the free plan, please adjust if needed
