# render.yaml
services:
  - type: web
    plan: free
    name: backend
    runtime: docker
    repo: https://github.com/captain0jay/Hault.git
    dockerfilePath: ./backend/Dockerfile
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 4000
      - key: LLM
        sync: false
      - key: UI
        sync: false
      - key: OWNER_EMAIL
        sync: false
      - key: OWNER_PHONE_NUMBER
        sync: false
      - key: DATABASE_URL
        sync: false
      - key: REDIS_DATABASE_URL
        sync: false
      - key: TWILIO_PHONE_NUMBER
        sync: false
      - key: TWILIO_ACCOUNT_SID
        sync: false
      - key: TWILIO_AUTH_TOKEN
        sync: false
      - key: GOOGLE_API_KEY
        sync: false
      - key: CLOUDFLARE_APP_ID
        sync: false
      - key: CLOUDFLARE_API_TOKEN
        sync: false
      - key: GOOGLE_CLIENT_ID
        sync: false
      - key: GOOGLE_CLIENT_SECRET
        sync: false
      - key: GOOGLE_REDIRECT_URI
        sync: false
      - key: JWT_SECRET_KEY
        sync: false
      - key: AIRTABLE_TABLE_ID
        sync: false
      - key: AIRTABLE_BASE_ID
        sync: false
      - key: AIRTABLE_API_KEY
        sync: false
      - key: RULES
        value: 'You are an AI support assistant for my company and are only allowed to answer questions related to context i have given you, normal grettings is fine speak like a support assistant on behalf of my company, your responses go directly to my customers so in no response should you be addressing me you are to talk with the users o my application only, ignore lowercase and uppercase ake all lowercase and when you dont have any answer say that we dont have the answer to that right now we will get back to you later'

  # - type: web
  #   name: frontend
  #   runtime: docker
  #   dockerfilePath: ./frontend/Dockerfile
  #   envVars:
  #     - key: NODE_ENV
  #       value: development
  #   port: 3000

  # - type: redis
  #   name: redis
  #   plan: free  # Assuming Redis can use the free plan, please adjust if needed

  # - type: mongodb
  #   name: mongodb
  #   plan: free  # Assuming MongoDB can use the free plan, please adjust if needed
